# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8100efd0e55cde51ad3f67c27533d44ebde5e72f9033d7b1613fba58fc77bce2d6bfb617dd39f1430263bed7b0eedd79f4a745d48a468fe4487769b20f000b6

test:
  secret_key_base: 1618ebade0fde45890e2f3d807891ac334ff7820ed4cd9a0bd3ee6c058cb272fb9b6ad72d9c85406bf6cdc2ae5ffd48685b6c6255ba5bf017c8fbdddd42e542b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
